apiVersion: v1
kind: Pod
metadata:
  name: xyz-pod
spec:
  tolerations:
    - key: "key"
      operator: "Equal"
      value: "value"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: ip-172-31-21-55  # Change to your actual node name
  containers:
    - name: busybox-container
      image: busybox
      command: [ "sleep", "3600" ]
      volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /etc/secret
          name: secret-volume
          readOnly: true
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: xyz-pvc
    - name: secret-volume
      secret:
        secretName: xyz-secret